server:
  port: 8089
  servlet:
    context-path: /example

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Example
  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      connectionTimeout: 30000 #30s
      idleTimeout: 600000 #10 minutes
      maxLifetime: 1800000 #30 minutes
      minimumIdle: 10
      maximumPoolSize: 5

